[package]
name = "extrautils"
version = "0.1.0"
authors = ["Ticki <Ticki@users.noreply.github.com>"]

[[bin]]
name = "mtxt"
path = "src/bin/mtxt.rs"

[[bin]]
name = "calc"
path = "src/bin/calc.rs"

[[bin]]
name = "cur"
path = "src/bin/cur.rs"

[[bin]]
name = "cksum"
path = "src/bin/cksum.rs"

[[bin]]
name = "grep"
path = "src/bin/grep.rs"

[[bin]]
name = "rem"
path = "src/bin/rem.rs"

[[bin]]
name = "less"
path = "src/bin/less.rs"

[dependencies.coreutils]
git = "https://github.com/redox-os/coreutils.git"

[dependencies.termion]
git = "https://github.com/Ticki/termion.git"
features = ["nightly"]
