[package]
name = "extrautils"
version = "0.1.0"
authors = ["Ticki <Ticki@users.noreply.github.com>"]

[[bin]]
name = "sc"
path = "src/bin/sc.rs"

[[bin]]
name = "mtxt"
path = "src/bin/mtxt.rs"

[[bin]]
name = "cur"
path = "src/bin/cur.rs"

[dependencies.coreutils]
git = "https://github.com/redox-os/coreutils.git"
