[package]
name = "extrautils"
version = "0.1.0"
authors = ["Ticki <Ticki@users.noreply.github.com>"]

[[bin]]
name = "mtxt"
path = "src/bin/mtxt.rs"

[[bin]]
name = "cur"
path = "src/bin/cur.rs"

[[bin]]
name = "cksum"
path = "src/bin/cksum.rs"

[[bin]]
name = "rem"
path = "src/bin/rem.rs"

[dependencies.extra]
git = "https://github.com/redox-os/libextra.git"
